name: biothings-annotator
services:
  annotator:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - ARG ANNOTATOR_REPO=https://github.com/biothings/biothings_annotator.git
        - ARG ANNOTATOR_BRANCH=main
    container_name: biothings-annotator
    ports:
      - 9001:9001
    networks:
      - annotator-network

  caddy:
    image: caddy:2.8-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
    depends_on:
      - annotator
    networks:
      - annotator-network

networks:
  annotator-network:
    driver: bridge
