name: biothings-annotator
services:
  annotator:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - ARG ANNOTATOR_REPO=https://github.com/biothings/biothings_annotator.git
        - ARG ANNOTATOR_BRANCH=main
    container_name: biothings-annotator
    ports:
      - 9000:9000

