apiVersion: v1
kind: Service
metadata:
  name: {{ include "biothings-annotator.fullname" . }}
  labels:
    {{- include "biothings-annotator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containers.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "biothings-annotator.selectorLabels" . | nindent 4 }}
